In [1]:
import pandas as pd 
import numpy as np

In [15]:
df = pd.read_csv('../data/gapminder.csv')

In [16]:
df.head()

,population,fertility,HIV,CO2,BMI_male,GDP,BMI_female,life,child_mortality,Region
0,34811059.0,2.73,0.1,3.328945,24.59620,12314.0,129.9049,75.3,29.5,Middle East & North Africa
1,19842251.0,6.43,2.0,1.474353,22.25083,7103.0,130.1247,58.3,192.0,Sub-Saharan Africa
2,40381860.0,2.24,0.5,4.785170,27.50170,14646.0,118.8915,75.5,15.4,America
3,2975029.0,1.40,0.1,1.804106,25.35542,7383.0,132.8108,72.5,20.0,Europe & Central Asia
4,21370348.0,1.96,0.1,18.016313,27.56373,41312.0,117.3755,81.5,5.2,East Asia & Pacific

In [17]:
# shape 
df.shape

(139, 10)

In [18]:
# columns 
df.columns

Index(['population', 'fertility', 'HIV', 'CO2', 'BMI_male', 'GDP',
       'BMI_female', 'life', 'child_mortality', 'Region'],
      dtype='object')

In [19]:
# dtypes 
df.dtypes

population         float64
fertility          float64
HIV                float64
CO2                float64
BMI_male           float64
GDP                float64
BMI_female         float64
life               float64
child_mortality    float64
Region              object
dtype: object

In [20]:
# info 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 139 entries, 0 to 138
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   population       139 non-null    float64
 1   fertility        139 non-null    float64
 2   HIV              139 non-null    float64
 3   CO2              139 non-null    float64
 4   BMI_male         139 non-null    float64
 5   GDP              139 non-null    float64
 6   BMI_female       139 non-null    float64
 7   life             139 non-null    float64
 8   child_mortality  139 non-null    float64
 9   Region           139 non-null    object
dtypes: float64(9), object(1)
memory usage: 11.0+ KB

In [21]:
# summary 
df.describe().T

,count,mean,std,min,25%,50%,75%,max
population,139.0,3.549977e+07,1.095121e+08,277315.000000,3.752776e+06,9.705130e+06,2.791973e+07,1.197070e+09
fertility,139.0,3.005108e+00,1.615354e+00,1.280000,1.810000e+00,2.410000e+00,4.095000e+00,7.590000e+00
HIV,139.0,1.915612e+00,4.408974e+00,0.060000,1.000000e-01,4.000000e-01,1.300000e+00,2.590000e+01
CO2,139.0,4.459874e+00,6.268349e+00,0.008618,4.961900e-01,2.223796e+00,6.589156e+00,4.870206e+01
BMI_male,139.0,2.462305e+01,2.209368e+00,20.397420,2.244814e+01,2.515699e+01,2.649757e+01,2.845698e+01
GDP,139.0,1.663878e+04,1.920730e+04,588.000000,2.899000e+03,9.938000e+03,2.327850e+04,1.260760e+05
BMI_female,139.0,1.267019e+02,4.471997e+00,117.375500,1.232322e+02,1.265196e+02,1.302759e+02,1.354920e+02
life,139.0,6.960288e+01,9.122189e+00,45.200000,6.220000e+01,7.200000e+01,7.685000e+01,8.260000e+01
child_mortality,139.0,4.509712e+01,4.572467e+01,2.700000,8.100000e+00,2.400000e+01,7.420000e+01,1.920000e+02

In [22]:
df['population'].astype('int64')

0      34811059
1      19842251
2      40381860
3       2975029
4      21370348
         ...
134     3350832
135    26952719
136    86589342
137    13114579
138    13495462
Name: population, Length: 139, dtype: int64

In [ ]:
# convert 
col.astype('dtype')

In [23]:
df.columns

Index(['population', 'fertility', 'HIV', 'CO2', 'BMI_male', 'GDP',
       'BMI_female', 'life', 'child_mortality', 'Region'],
      dtype='object')

In [24]:
df.columns.str.upper()

Index(['POPULATION', 'FERTILITY', 'HIV', 'CO2', 'BMI_MALE', 'GDP',
       'BMI_FEMALE', 'LIFE', 'CHILD_MORTALITY', 'REGION'],
      dtype='object')

In [25]:
df.columns.str.capitalize()

Index(['Population', 'Fertility', 'Hiv', 'Co2', 'Bmi_male', 'Gdp',
       'Bmi_female', 'Life', 'Child_mortality', 'Region'],
      dtype='object')

In [26]:
df = pd.read_csv('../data/kidney_disease.csv')

In [27]:
df.head()

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,35,7300,4.6,no,no,no,good,no,no,ckd

In [28]:
# shape 
df.shape

(400, 26)

In [33]:
mask = df['age'] < 20

In [34]:
df[mask]

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,...,38,6000,NaN,no,no,no,good,no,no,ckd
47,47,11.0,80.0,1.010,3.0,0.0,NaN,normal,notpresent,notpresent,...,45,8600,NaN,no,no,no,good,no,no,ckd
62,62,15.0,60.0,1.020,3.0,0.0,NaN,normal,notpresent,notpresent,...,33,7700,3.8,yes,yes,no,good,no,no,ckd
75,75,5.0,NaN,1.015,1.0,0.0,NaN,normal,notpresent,notpresent,...,NaN,NaN,NaN,no,no,no,good,no,yes,ckd
102,102,17.0,60.0,1.010,0.0,0.0,NaN,normal,notpresent,notpresent,...,52,7000,NaN,no,no,no,good,no,no,ckd
114,114,12.0,60.0,1.015,3.0,0.0,abnormal,abnormal,present,notpresent,...,NaN,10300,NaN,no,no,no,good,no,no,ckd
131,131,5.0,50.0,1.010,0.0,0.0,NaN,normal,notpresent,notpresent,...,36,12400,NaN,no,no,no,good,no,no,ckd
150,150,8.0,60.0,1.025,3.0,0.0,normal,normal,notpresent,notpresent,...,41,6700,NaN,no,no,no,poor,yes,no,ckd
164,164,14.0,NaN,1.015,0.0,0.0,NaN,NaN,notpresent,notpresent,...,40,9500,5.4,no,yes,no,poor,yes,no,ckd
173,173,17.0,70.0,1.015,1.0,0.0,abnormal,normal,notpresent,notpresent,...,41,11200,NaN,no,no,no,good,no,no,ckd
185,185,4.0,NaN,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,...,34,\t?,NaN,no,no,no,good,no,no,ckd
186,186,8.0,50.0,1.020,4.0,0.0,normal,normal,notpresent,notpresent,...,NaN,NaN,NaN,no,no,no,good,yes,no,ckd
187,187,3.0,NaN,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,34,12300,NaN,no,no,no,good,no,no,ckd
188,188,8.0,NaN,NaN,NaN,NaN,NaN,NaN,notpresent,notpresent,...,38,NaN,NaN,no,\tno,no,good,no,no,ckd
190,190,6.0,60.0,1.010,4.0,0.0,abnormal,abnormal,notpresent,present,...,30,16700,4.8,no,no,no,poor,no,no,ckd
209,209,19.0,70.0,1.020,0.0,0.0,NaN,normal,notpresent,notpresent,...,NaN,6900,NaN,no,no,no,good,no,no,ckd
215,215,2.0,NaN,1.010,3.0,0.0,normal,abnormal,notpresent,notpresent,...,NaN,NaN,NaN,no,no,no,good,yes,no,ckd
274,274,19.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,44,NaN,NaN,no,no,no,good,no,no,notckd
387,387,15.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,50,6200,5.2,no,no,no,good,no,no,notckd
397,397,12.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,49,6600,5.4,no,no,no,good,no,no,notckd
398,398,17.0,60.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,51,7200,5.9,no,no,no,good,no,no,notckd

In [31]:
df[df['age'] < 20]

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,...,38,6000,NaN,no,no,no,good,no,no,ckd
47,47,11.0,80.0,1.010,3.0,0.0,NaN,normal,notpresent,notpresent,...,45,8600,NaN,no,no,no,good,no,no,ckd
62,62,15.0,60.0,1.020,3.0,0.0,NaN,normal,notpresent,notpresent,...,33,7700,3.8,yes,yes,no,good,no,no,ckd
75,75,5.0,NaN,1.015,1.0,0.0,NaN,normal,notpresent,notpresent,...,NaN,NaN,NaN,no,no,no,good,no,yes,ckd
102,102,17.0,60.0,1.010,0.0,0.0,NaN,normal,notpresent,notpresent,...,52,7000,NaN,no,no,no,good,no,no,ckd
114,114,12.0,60.0,1.015,3.0,0.0,abnormal,abnormal,present,notpresent,...,NaN,10300,NaN,no,no,no,good,no,no,ckd
131,131,5.0,50.0,1.010,0.0,0.0,NaN,normal,notpresent,notpresent,...,36,12400,NaN,no,no,no,good,no,no,ckd
150,150,8.0,60.0,1.025,3.0,0.0,normal,normal,notpresent,notpresent,...,41,6700,NaN,no,no,no,poor,yes,no,ckd
164,164,14.0,NaN,1.015,0.0,0.0,NaN,NaN,notpresent,notpresent,...,40,9500,5.4,no,yes,no,poor,yes,no,ckd
173,173,17.0,70.0,1.015,1.0,0.0,abnormal,normal,notpresent,notpresent,...,41,11200,NaN,no,no,no,good,no,no,ckd
185,185,4.0,NaN,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,...,34,\t?,NaN,no,no,no,good,no,no,ckd
186,186,8.0,50.0,1.020,4.0,0.0,normal,normal,notpresent,notpresent,...,NaN,NaN,NaN,no,no,no,good,yes,no,ckd
187,187,3.0,NaN,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,34,12300,NaN,no,no,no,good,no,no,ckd
188,188,8.0,NaN,NaN,NaN,NaN,NaN,NaN,notpresent,notpresent,...,38,NaN,NaN,no,\tno,no,good,no,no,ckd
190,190,6.0,60.0,1.010,4.0,0.0,abnormal,abnormal,notpresent,present,...,30,16700,4.8,no,no,no,poor,no,no,ckd
209,209,19.0,70.0,1.020,0.0,0.0,NaN,normal,notpresent,notpresent,...,NaN,6900,NaN,no,no,no,good,no,no,ckd
215,215,2.0,NaN,1.010,3.0,0.0,normal,abnormal,notpresent,notpresent,...,NaN,NaN,NaN,no,no,no,good,yes,no,ckd
274,274,19.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,44,NaN,NaN,no,no,no,good,no,no,notckd
387,387,15.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,50,6200,5.2,no,no,no,good,no,no,notckd
397,397,12.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,49,6600,5.4,no,no,no,good,no,no,notckd
398,398,17.0,60.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,51,7200,5.9,no,no,no,good,no,no,notckd

In [43]:
df[(df['age'] < 20) | (df['age'] > 25)]

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,47,6700,4.9,no,no,no,good,no,no,notckd
396,396,42.0,70.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,54,7800,6.2,no,no,no,good,no,no,notckd
397,397,12.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,49,6600,5.4,no,no,no,good,no,no,notckd
398,398,17.0,60.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,51,7200,5.9,no,no,no,good,no,no,notckd
399,399,58.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,53,6800,6.1,no,no,no,good,no,no,notckd

In [44]:
df[(df['age'] < 20) & (df['age'] > 25)]

Empty DataFrame
Columns: [id, age, bp, sg, al, su, rbc, pc, pcc, ba, bgr, bu, sc, sod, pot, hemo, pcv, wc, rc, htn, dm, cad, appet, pe, ane, classification]
Index: []

[0 rows x 26 columns]

In [47]:
df['appet'].unique()

array(['good', 'poor', nan], dtype=object)

In [48]:
good_df = df[df['appet'] == 'good']

In [50]:
good_df.to_csv('../data/good_df.csv', index=False)

In [51]:
bad_df = df[df['appet'] == 'bad']

In [53]:
bad_df.to_csv('../data/bad_df.csv', index=False)

In [54]:
df = pd.read_csv('../data/diabetes.csv')

In [55]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [58]:
df[(df['BMI'] > 18.5) & (df['BMI'] < 20.5)]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
33,6,92,92,0,0,19.9,0.188,28,0
50,1,103,80,11,82,19.4,0.491,22,0
68,1,95,66,13,38,19.6,0.334,25,0
90,1,80,55,0,0,19.1,0.258,21,0
97,1,71,48,18,76,20.4,0.323,22,0
203,2,99,70,16,44,20.4,0.235,27,0
316,3,99,80,11,64,19.3,0.284,30,0
381,0,105,68,22,0,20.0,0.236,22,0
453,2,119,0,0,0,19.6,0.832,72,0
519,6,129,90,7,326,19.6,0.582,60,0
607,1,92,62,25,41,19.5,0.482,25,0
617,2,68,62,13,15,20.1,0.257,23,0
639,1,100,74,12,46,19.5,0.149,28,0

In [60]:
df[(df['Age'] > 18) & (df['Age'] < 20)]

Empty DataFrame
Columns: [Pregnancies, Glucose, BloodPressure, SkinThickness, Insulin, BMI, DiabetesPedigreeFunction, Age, Outcome]
Index: []